/////clsDBInteractionQLDH
///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'DM_KhachHang_Test'
// Generated by LLBLGen v1.3.5996.26197 Final on: Tuesday, December 2, 2025, 5:59:54 PM
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;
using GMS.ConnectionProviders;

namespace GMS_Test
{
	/// <summary>
	/// Purpose: Data Access class for the table 'DM_KhachHang_Test'.
	/// </summary>
	public partial class clsDM_KhachHang_Test : clsDBInteractionQLDH
	{
		#region Class Member Declarations
		private SqlBoolean m_bIsSuDung, m_bIsTonTai;
		private SqlDateTime m_daNgaySuaCuoi, m_daNgayNhap;
		private SqlInt32 m_iID_KhachHang;
		private SqlString m_sTenKhachHang;
		private SqlByte m_byTrangThai, m_byID_LoaiKhachHang;
		#endregion


		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public clsDM_KhachHang_Test()
		{
			// Nothing for now.
		}


		/// <summary>
		/// Purpose: Insert method. This method will insert one new row into the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_LoaiKhachHang</LI>
		///		 <LI>TenKhachHang</LI>
		///		 <LI>TrangThai</LI>
		///		 <LI>IsTonTai</LI>
		///		 <LI>IsSuDung. May be SqlBoolean.Null</LI>
		///		 <LI>NgayNhap. May be SqlDateTime.Null</LI>
		///		 <LI>NgaySuaCuoi. May be SqlDateTime.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ID_KhachHang</LI>
		/// </UL>
		/// </remarks>
		public override bool Insert()
		{
			SqlCommand scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_KhachHang_Test_Insert]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_LoaiKhachHang", SqlDbType.TinyInt, 1, ParameterDirection.Input, false, 3, 0, "", DataRowVersion.Proposed, m_byID_LoaiKhachHang));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@TenKhachHang", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_sTenKhachHang));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@TrangThai", SqlDbType.TinyInt, 1, ParameterDirection.Input, false, 3, 0, "", DataRowVersion.Proposed, m_byTrangThai));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsTonTai", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsTonTai));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsSuDung", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsSuDung));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@NgayNhap", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_daNgayNhap));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@NgaySuaCuoi", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_daNgaySuaCuoi));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_KhachHang", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, m_iID_KhachHang));

				if (m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if (m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				scmCmdToExecute.ExecuteNonQuery();
				m_iID_KhachHang = (SqlInt32)scmCmdToExecute.Parameters["@ID_KhachHang"].Value;
				return true;
			}
			catch (Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_KhachHang_Test::Insert::Error occured.", ex);
			}
			finally
			{
				if (m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Update method. This method will Update one existing row in the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_KhachHang</LI>
		///		 <LI>ID_LoaiKhachHang</LI>
		///		 <LI>TenKhachHang</LI>
		///		 <LI>TrangThai</LI>
		///		 <LI>IsTonTai</LI>
		///		 <LI>IsSuDung. May be SqlBoolean.Null</LI>
		///		 <LI>NgayNhap. May be SqlDateTime.Null</LI>
		///		 <LI>NgaySuaCuoi. May be SqlDateTime.Null</LI>
		/// </UL>
		/// </remarks>
		public override bool Update()
		{
			SqlCommand scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_KhachHang_Test_Update]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_KhachHang", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, m_iID_KhachHang));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_LoaiKhachHang", SqlDbType.TinyInt, 1, ParameterDirection.Input, false, 3, 0, "", DataRowVersion.Proposed, m_byID_LoaiKhachHang));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@TenKhachHang", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_sTenKhachHang));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@TrangThai", SqlDbType.TinyInt, 1, ParameterDirection.Input, false, 3, 0, "", DataRowVersion.Proposed, m_byTrangThai));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsTonTai", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsTonTai));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsSuDung", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsSuDung));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@NgayNhap", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_daNgayNhap));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@NgaySuaCuoi", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_daNgaySuaCuoi));

				if (m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if (m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				scmCmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch (Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_KhachHang_Test::Update::Error occured.", ex);
			}
			finally
			{
				if (m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Delete method. This method will Delete one existing row in the database, based on the Primary Key.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_KhachHang</LI>
		/// </UL>
		/// </remarks>
		public override bool Delete()
		{
			SqlCommand scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_KhachHang_Test_Delete]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_KhachHang", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, m_iID_KhachHang));

				if (m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if (m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				scmCmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch (Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_KhachHang_Test::Delete::Error occured.", ex);
			}
			finally
			{
				if (m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method. This method will Select one existing row from the database, based on the Primary Key.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_KhachHang</LI>
		/// </UL>
		///		 <LI>ID_KhachHang</LI>
		///		 <LI>ID_LoaiKhachHang</LI>
		///		 <LI>TenKhachHang</LI>
		///		 <LI>TrangThai</LI>
		///		 <LI>IsTonTai</LI>
		///		 <LI>IsSuDung</LI>
		///		 <LI>NgayNhap</LI>
		///		 <LI>NgaySuaCuoi</LI>
		/// Will fill all properties corresponding with a field in the table with the value of the row selected.
		/// </remarks>
		public override DataTable SelectOne()
		{
			SqlCommand scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_KhachHang_Test_SelectOne]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable dtToReturn = new DataTable("DM_KhachHang_Test");
			SqlDataAdapter sdaAdapter = new SqlDataAdapter(scmCmdToExecute);

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_KhachHang", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, m_iID_KhachHang));

				if (m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if (m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				sdaAdapter.Fill(dtToReturn);
				if (dtToReturn.Rows.Count > 0)
				{
					m_iID_KhachHang = (Int32)dtToReturn.Rows[0]["ID_KhachHang"];
					m_byID_LoaiKhachHang = (byte)dtToReturn.Rows[0]["ID_LoaiKhachHang"];
					m_sTenKhachHang = (string)dtToReturn.Rows[0]["TenKhachHang"];
					m_byTrangThai = (byte)dtToReturn.Rows[0]["TrangThai"];
					m_bIsTonTai = (bool)dtToReturn.Rows[0]["IsTonTai"];
					m_bIsSuDung = dtToReturn.Rows[0]["IsSuDung"] == System.DBNull.Value ? SqlBoolean.Null : (bool)dtToReturn.Rows[0]["IsSuDung"];
					m_daNgayNhap = dtToReturn.Rows[0]["NgayNhap"] == System.DBNull.Value ? SqlDateTime.Null : (DateTime)dtToReturn.Rows[0]["NgayNhap"];
					m_daNgaySuaCuoi = dtToReturn.Rows[0]["NgaySuaCuoi"] == System.DBNull.Value ? SqlDateTime.Null : (DateTime)dtToReturn.Rows[0]["NgaySuaCuoi"];
				}
				return dtToReturn;
			}
			catch (Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_KhachHang_Test::SelectOne::Error occured.", ex);
			}
			finally
			{
				if (m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
				sdaAdapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: SelectAll method. This method will Select all rows from the table.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// </remarks>
		public override DataTable SelectAll()
		{
			SqlCommand scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_KhachHang_Test_SelectAll]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable dtToReturn = new DataTable("DM_KhachHang_Test");
			SqlDataAdapter sdaAdapter = new SqlDataAdapter(scmCmdToExecute);

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{

				if (m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if (m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				sdaAdapter.Fill(dtToReturn);
				return dtToReturn;
			}
			catch (Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_KhachHang_Test::SelectAll::Error occured.", ex);
			}
			finally
			{
				if (m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
				sdaAdapter.Dispose();
			}
		}


		#region Class Property Declarations
		public SqlInt32 ID_KhachHang
		{
			get
			{
				return m_iID_KhachHang;
			}
			set
			{
				SqlInt32 iID_KhachHangTmp = (SqlInt32)value;
				if (iID_KhachHangTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("iD_KhachHang", "iD_KhachHang can't be NULL");
				}
				m_iID_KhachHang = value;
			}
		}


		public SqlByte ID_LoaiKhachHang
		{
			get
			{
				return m_byID_LoaiKhachHang;
			}
			set
			{
				SqlByte byID_LoaiKhachHangTmp = (SqlByte)value;
				if (byID_LoaiKhachHangTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("iD_LoaiKhachHang", "iD_LoaiKhachHang can't be NULL");
				}
				m_byID_LoaiKhachHang = value;
			}
		}


		public SqlString TenKhachHang
		{
			get
			{
				return m_sTenKhachHang;
			}
			set
			{
				SqlString sTenKhachHangTmp = (SqlString)value;
				if (sTenKhachHangTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("tenKhachHang", "tenKhachHang can't be NULL");
				}
				m_sTenKhachHang = value;
			}
		}


		public SqlByte TrangThai
		{
			get
			{
				return m_byTrangThai;
			}
			set
			{
				SqlByte byTrangThaiTmp = (SqlByte)value;
				if (byTrangThaiTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("trangThai", "trangThai can't be NULL");
				}
				m_byTrangThai = value;
			}
		}


		public SqlBoolean IsTonTai
		{
			get
			{
				return m_bIsTonTai;
			}
			set
			{
				SqlBoolean bIsTonTaiTmp = (SqlBoolean)value;
				if (bIsTonTaiTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("isTonTai", "isTonTai can't be NULL");
				}
				m_bIsTonTai = value;
			}
		}


		public SqlBoolean IsSuDung
		{
			get
			{
				return m_bIsSuDung;
			}
			set
			{
				m_bIsSuDung = value;
			}
		}


		public SqlDateTime NgayNhap
		{
			get
			{
				return m_daNgayNhap;
			}
			set
			{
				m_daNgayNhap = value;
			}
		}


		public SqlDateTime NgaySuaCuoi
		{
			get
			{
				return m_daNgaySuaCuoi;
			}
			set
			{
				m_daNgaySuaCuoi = value;
			}
		}
		#endregion
	}
}

