///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'DM_Kho'
// Generated by LLBLGen v1.3.5996.26197 Final on: Saturday, December 6, 2025, 9:29:06 AM
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;
using VSCM.Base.Classes;

namespace GMS_Test
{
	/// <summary>
	/// Purpose: Data Access class for the table 'DM_Kho'.
	/// </summary>
	public partial class clsDM_Kho : clsDBInteractionBase
	{
		#region Class Member Declarations
			private SqlBoolean		m_bIsSuDung, m_bIsTonTai;
			private SqlString		m_sTenKho;
			private SqlInt16		m_siID_Kho, m_siSTTKho, m_siID_DonVi;
			private SqlByte			m_byLoaiKho;
		#endregion


		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public clsDM_Kho()
		{
			// Nothing for now.
		}


		/// <summary>
		/// Purpose: Insert method. This method will insert one new row into the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_Kho</LI>
		///		 <LI>LoaiKho</LI>
		///		 <LI>TenKho</LI>
		///		 <LI>ID_DonVi</LI>
		///		 <LI>STTKho</LI>
		///		 <LI>IsSuDung</LI>
		///		 <LI>IsTonTai</LI>
		/// </UL>
		/// </remarks>
		public override bool Insert()
		{
			SqlCommand	scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_Kho_Insert]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_Kho", SqlDbType.SmallInt, 2, ParameterDirection.Input, false, 5, 0, "", DataRowVersion.Proposed, m_siID_Kho));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@LoaiKho", SqlDbType.TinyInt, 1, ParameterDirection.Input, false, 3, 0, "", DataRowVersion.Proposed, m_byLoaiKho));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@TenKho", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_sTenKho));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_DonVi", SqlDbType.SmallInt, 2, ParameterDirection.Input, false, 5, 0, "", DataRowVersion.Proposed, m_siID_DonVi));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@STTKho", SqlDbType.SmallInt, 2, ParameterDirection.Input, false, 5, 0, "", DataRowVersion.Proposed, m_siSTTKho));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsSuDung", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsSuDung));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsTonTai", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsTonTai));

				if(m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if(m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				scmCmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_Kho::Insert::Error occured.", ex);
			}
			finally
			{
				if(m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Update method. This method will Update one existing row in the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_Kho</LI>
		///		 <LI>LoaiKho</LI>
		///		 <LI>TenKho</LI>
		///		 <LI>ID_DonVi</LI>
		///		 <LI>STTKho</LI>
		///		 <LI>IsSuDung</LI>
		///		 <LI>IsTonTai</LI>
		/// </UL>
		/// </remarks>
		public override bool Update()
		{
			SqlCommand	scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_Kho_Update]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_Kho", SqlDbType.SmallInt, 2, ParameterDirection.Input, false, 5, 0, "", DataRowVersion.Proposed, m_siID_Kho));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@LoaiKho", SqlDbType.TinyInt, 1, ParameterDirection.Input, false, 3, 0, "", DataRowVersion.Proposed, m_byLoaiKho));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@TenKho", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_sTenKho));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_DonVi", SqlDbType.SmallInt, 2, ParameterDirection.Input, false, 5, 0, "", DataRowVersion.Proposed, m_siID_DonVi));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@STTKho", SqlDbType.SmallInt, 2, ParameterDirection.Input, false, 5, 0, "", DataRowVersion.Proposed, m_siSTTKho));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsSuDung", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsSuDung));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsTonTai", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsTonTai));

				if(m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if(m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				scmCmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_Kho::Update::Error occured.", ex);
			}
			finally
			{
				if(m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Delete method. This method will Delete one existing row in the database, based on the Primary Key.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_Kho</LI>
		/// </UL>
		/// </remarks>
		public override bool Delete()
		{
			SqlCommand	scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_Kho_Delete]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_Kho", SqlDbType.SmallInt, 2, ParameterDirection.Input, false, 5, 0, "", DataRowVersion.Proposed, m_siID_Kho));

				if(m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if(m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				scmCmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_Kho::Delete::Error occured.", ex);
			}
			finally
			{
				if(m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method. This method will Select one existing row from the database, based on the Primary Key.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_Kho</LI>
		/// </UL>
		///		 <LI>ID_Kho</LI>
		///		 <LI>LoaiKho</LI>
		///		 <LI>TenKho</LI>
		///		 <LI>ID_DonVi</LI>
		///		 <LI>STTKho</LI>
		///		 <LI>IsSuDung</LI>
		///		 <LI>IsTonTai</LI>
		/// Will fill all properties corresponding with a field in the table with the value of the row selected.
		/// </remarks>
		public override DataTable SelectOne()
		{
			SqlCommand	scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_Kho_SelectOne]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable dtToReturn = new DataTable("DM_Kho");
			SqlDataAdapter sdaAdapter = new SqlDataAdapter(scmCmdToExecute);

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_Kho", SqlDbType.SmallInt, 2, ParameterDirection.Input, false, 5, 0, "", DataRowVersion.Proposed, m_siID_Kho));

				if(m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if(m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				sdaAdapter.Fill(dtToReturn);
				if(dtToReturn.Rows.Count > 0)
				{
					m_siID_Kho = (Int16)dtToReturn.Rows[0]["ID_Kho"];
					m_byLoaiKho = (byte)dtToReturn.Rows[0]["LoaiKho"];
					m_sTenKho = (string)dtToReturn.Rows[0]["TenKho"];
					m_siID_DonVi = (Int16)dtToReturn.Rows[0]["ID_DonVi"];
					m_siSTTKho = (Int16)dtToReturn.Rows[0]["STTKho"];
					m_bIsSuDung = (bool)dtToReturn.Rows[0]["IsSuDung"];
					m_bIsTonTai = (bool)dtToReturn.Rows[0]["IsTonTai"];
				}
				return dtToReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_Kho::SelectOne::Error occured.", ex);
			}
			finally
			{
				if(m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
				sdaAdapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: SelectAll method. This method will Select all rows from the table.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// </remarks>
		public override DataTable SelectAll()
		{
			SqlCommand	scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_Kho_SelectAll]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable dtToReturn = new DataTable("DM_Kho");
			SqlDataAdapter sdaAdapter = new SqlDataAdapter(scmCmdToExecute);

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{

				if(m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if(m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				sdaAdapter.Fill(dtToReturn);
				return dtToReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_Kho::SelectAll::Error occured.", ex);
			}
			finally
			{
				if(m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
				sdaAdapter.Dispose();
			}
		}


		#region Class Property Declarations
		public SqlInt16 ID_Kho
		{
			get
			{
				return m_siID_Kho;
			}
			set
			{
				SqlInt16 siID_KhoTmp = (SqlInt16)value;
				if(siID_KhoTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("iD_Kho", "iD_Kho can't be NULL");
				}
				m_siID_Kho = value;
			}
		}


		public SqlByte LoaiKho
		{
			get
			{
				return m_byLoaiKho;
			}
			set
			{
				SqlByte byLoaiKhoTmp = (SqlByte)value;
				if(byLoaiKhoTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("loaiKho", "loaiKho can't be NULL");
				}
				m_byLoaiKho = value;
			}
		}


		public SqlString TenKho
		{
			get
			{
				return m_sTenKho;
			}
			set
			{
				SqlString sTenKhoTmp = (SqlString)value;
				if(sTenKhoTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("tenKho", "tenKho can't be NULL");
				}
				m_sTenKho = value;
			}
		}


		public SqlInt16 ID_DonVi
		{
			get
			{
				return m_siID_DonVi;
			}
			set
			{
				SqlInt16 siID_DonViTmp = (SqlInt16)value;
				if(siID_DonViTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("iD_DonVi", "iD_DonVi can't be NULL");
				}
				m_siID_DonVi = value;
			}
		}


		public SqlInt16 STTKho
		{
			get
			{
				return m_siSTTKho;
			}
			set
			{
				SqlInt16 siSTTKhoTmp = (SqlInt16)value;
				if(siSTTKhoTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("sTTKho", "sTTKho can't be NULL");
				}
				m_siSTTKho = value;
			}
		}


		public SqlBoolean IsSuDung
		{
			get
			{
				return m_bIsSuDung;
			}
			set
			{
				SqlBoolean bIsSuDungTmp = (SqlBoolean)value;
				if(bIsSuDungTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("isSuDung", "isSuDung can't be NULL");
				}
				m_bIsSuDung = value;
			}
		}


		public SqlBoolean IsTonTai
		{
			get
			{
				return m_bIsTonTai;
			}
			set
			{
				SqlBoolean bIsTonTaiTmp = (SqlBoolean)value;
				if(bIsTonTaiTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("isTonTai", "isTonTai can't be NULL");
				}
				m_bIsTonTai = value;
			}
		}
		#endregion
	}
}
