///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'DM_Thung'
// Generated by LLBLGen v1.3.5996.26197 Final on: Friday, December 5, 2025, 10:50:25 PM
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;
using VSCM.Base.Classes;

namespace GMS_Test
{
	/// <summary>
	/// Purpose: Data Access class for the table 'DM_Thung'.
	/// </summary>
	public partial class clsDM_Thung : clsDBInteractionBase
	{
		#region Class Member Declarations
			private SqlBoolean		m_bIsTonTai, m_bIsSuDung;
			private SqlDateTime		m_daNgaySuaCuoi, m_daNgayNhap;
			private SqlInt32		m_iID_Thung, m_iID_Kho;
			private SqlString		m_sMaThung, m_sTenThung;
		#endregion


		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public clsDM_Thung()
		{
			// Nothing for now.
		}


		/// <summary>
		/// Purpose: Insert method. This method will insert one new row into the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>MaThung. May be SqlString.Null</LI>
		///		 <LI>TenThung</LI>
		///		 <LI>ID_Kho. May be SqlInt32.Null</LI>
		///		 <LI>IsSuDung. May be SqlBoolean.Null</LI>
		///		 <LI>IsTonTai. May be SqlBoolean.Null</LI>
		///		 <LI>NgayNhap</LI>
		///		 <LI>NgaySuaCuoi. May be SqlDateTime.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ID_Thung</LI>
		/// </UL>
		/// </remarks>
		public override bool Insert()
		{
			SqlCommand	scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_Thung_Insert]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@MaThung", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_sMaThung));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@TenThung", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_sTenThung));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_Kho", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, m_iID_Kho));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsSuDung", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsSuDung));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsTonTai", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsTonTai));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@NgayNhap", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_daNgayNhap));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@NgaySuaCuoi", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_daNgaySuaCuoi));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_Thung", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, m_iID_Thung));

				if(m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if(m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				scmCmdToExecute.ExecuteNonQuery();
				m_iID_Thung = (SqlInt32)scmCmdToExecute.Parameters["@ID_Thung"].Value;
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_Thung::Insert::Error occured.", ex);
			}
			finally
			{
				if(m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Update method. This method will Update one existing row in the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_Thung</LI>
		///		 <LI>MaThung. May be SqlString.Null</LI>
		///		 <LI>TenThung</LI>
		///		 <LI>ID_Kho. May be SqlInt32.Null</LI>
		///		 <LI>IsSuDung. May be SqlBoolean.Null</LI>
		///		 <LI>IsTonTai. May be SqlBoolean.Null</LI>
		///		 <LI>NgayNhap</LI>
		///		 <LI>NgaySuaCuoi. May be SqlDateTime.Null</LI>
		/// </UL>
		/// </remarks>
		public override bool Update()
		{
			SqlCommand	scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_Thung_Update]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_Thung", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, m_iID_Thung));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@MaThung", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_sMaThung));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@TenThung", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_sTenThung));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_Kho", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, m_iID_Kho));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsSuDung", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsSuDung));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@IsTonTai", SqlDbType.Bit, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_bIsTonTai));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@NgayNhap", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_daNgayNhap));
				scmCmdToExecute.Parameters.Add(new SqlParameter("@NgaySuaCuoi", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, m_daNgaySuaCuoi));

				if(m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if(m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				scmCmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_Thung::Update::Error occured.", ex);
			}
			finally
			{
				if(m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Delete method. This method will Delete one existing row in the database, based on the Primary Key.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_Thung</LI>
		/// </UL>
		/// </remarks>
		public override bool Delete()
		{
			SqlCommand	scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_Thung_Delete]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_Thung", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, m_iID_Thung));

				if(m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if(m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				scmCmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_Thung::Delete::Error occured.", ex);
			}
			finally
			{
				if(m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method. This method will Select one existing row from the database, based on the Primary Key.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_Thung</LI>
		/// </UL>
		///		 <LI>ID_Thung</LI>
		///		 <LI>MaThung</LI>
		///		 <LI>TenThung</LI>
		///		 <LI>ID_Kho</LI>
		///		 <LI>IsSuDung</LI>
		///		 <LI>IsTonTai</LI>
		///		 <LI>NgayNhap</LI>
		///		 <LI>NgaySuaCuoi</LI>
		/// Will fill all properties corresponding with a field in the table with the value of the row selected.
		/// </remarks>
		public override DataTable SelectOne()
		{
			SqlCommand	scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_Thung_SelectOne]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable dtToReturn = new DataTable("DM_Thung");
			SqlDataAdapter sdaAdapter = new SqlDataAdapter(scmCmdToExecute);

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{
				scmCmdToExecute.Parameters.Add(new SqlParameter("@ID_Thung", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, m_iID_Thung));

				if(m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if(m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				sdaAdapter.Fill(dtToReturn);
				if(dtToReturn.Rows.Count > 0)
				{
					m_iID_Thung = (Int32)dtToReturn.Rows[0]["ID_Thung"];
					m_sMaThung = dtToReturn.Rows[0]["MaThung"] == System.DBNull.Value ? SqlString.Null : (string)dtToReturn.Rows[0]["MaThung"];
					m_sTenThung = (string)dtToReturn.Rows[0]["TenThung"];
					m_iID_Kho = dtToReturn.Rows[0]["ID_Kho"] == System.DBNull.Value ? SqlInt32.Null : (Int32)dtToReturn.Rows[0]["ID_Kho"];
					m_bIsSuDung = dtToReturn.Rows[0]["IsSuDung"] == System.DBNull.Value ? SqlBoolean.Null : (bool)dtToReturn.Rows[0]["IsSuDung"];
					m_bIsTonTai = dtToReturn.Rows[0]["IsTonTai"] == System.DBNull.Value ? SqlBoolean.Null : (bool)dtToReturn.Rows[0]["IsTonTai"];
					m_daNgayNhap = (DateTime)dtToReturn.Rows[0]["NgayNhap"];
					m_daNgaySuaCuoi = dtToReturn.Rows[0]["NgaySuaCuoi"] == System.DBNull.Value ? SqlDateTime.Null : (DateTime)dtToReturn.Rows[0]["NgaySuaCuoi"];
				}
				return dtToReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_Thung::SelectOne::Error occured.", ex);
			}
			finally
			{
				if(m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
				sdaAdapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: SelectAll method. This method will Select all rows from the table.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// </remarks>
		public override DataTable SelectAll()
		{
			SqlCommand	scmCmdToExecute = new SqlCommand();
			scmCmdToExecute.CommandText = "dbo.[pr_DM_Thung_SelectAll]";
			scmCmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable dtToReturn = new DataTable("DM_Thung");
			SqlDataAdapter sdaAdapter = new SqlDataAdapter(scmCmdToExecute);

			// Use base class' connection object
			scmCmdToExecute.Connection = m_scoMainConnection;

			try
			{

				if(m_bMainConnectionIsCreatedLocal)
				{
					// Open connection.
					m_scoMainConnection.Open();
				}
				else
				{
					if(m_cpMainConnectionProvider.IsTransactionPending)
					{
						scmCmdToExecute.Transaction = m_cpMainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				sdaAdapter.Fill(dtToReturn);
				return dtToReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("clsDM_Thung::SelectAll::Error occured.", ex);
			}
			finally
			{
				if(m_bMainConnectionIsCreatedLocal)
				{
					// Close connection.
					m_scoMainConnection.Close();
				}
				scmCmdToExecute.Dispose();
				sdaAdapter.Dispose();
			}
		}


		#region Class Property Declarations
		public SqlInt32 ID_Thung
		{
			get
			{
				return m_iID_Thung;
			}
			set
			{
				SqlInt32 iID_ThungTmp = (SqlInt32)value;
				if(iID_ThungTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("iD_Thung", "iD_Thung can't be NULL");
				}
				m_iID_Thung = value;
			}
		}


		public SqlString MaThung
		{
			get
			{
				return m_sMaThung;
			}
			set
			{
				m_sMaThung = value;
			}
		}


		public SqlString TenThung
		{
			get
			{
				return m_sTenThung;
			}
			set
			{
				SqlString sTenThungTmp = (SqlString)value;
				if(sTenThungTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("tenThung", "tenThung can't be NULL");
				}
				m_sTenThung = value;
			}
		}


		public SqlInt32 ID_Kho
		{
			get
			{
				return m_iID_Kho;
			}
			set
			{
				m_iID_Kho = value;
			}
		}


		public SqlBoolean IsSuDung
		{
			get
			{
				return m_bIsSuDung;
			}
			set
			{
				m_bIsSuDung = value;
			}
		}


		public SqlBoolean IsTonTai
		{
			get
			{
				return m_bIsTonTai;
			}
			set
			{
				m_bIsTonTai = value;
			}
		}


		public SqlDateTime NgayNhap
		{
			get
			{
				return m_daNgayNhap;
			}
			set
			{
				SqlDateTime daNgayNhapTmp = (SqlDateTime)value;
				if(daNgayNhapTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ngayNhap", "ngayNhap can't be NULL");
				}
				m_daNgayNhap = value;
			}
		}


		public SqlDateTime NgaySuaCuoi
		{
			get
			{
				return m_daNgaySuaCuoi;
			}
			set
			{
				m_daNgaySuaCuoi = value;
			}
		}
		#endregion
	}
}
